#!/bin/sh /etc/rc.common
START=98
STOP=10
USE_PROCD=1
start_service() {
    procd_open_instance
    procd_set_param command /etc/kk-car/dji-sms-forward-watch.sh
    procd_set_param respawn 3600 5 5
    procd_set_param term_timeout 15
    procd_close_instance
}
