#!/bin/sh /etc/rc.common
START=21
STOP=10
USE_PROCD=1
start_service() {
    procd_open_instance
    procd_set_param command /bin/sh /etc/kk-car/uplink-watch.sh
    procd_set_param respawn 3600 5 5
    procd_set_param stderr 1
    procd_close_instance
}
