#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1
start_service() {
    procd_open_instance
    procd_set_param command /etc/kk-car/auto-check.sh
    procd_set_param nice 10
    procd_set_param respawn 3600 30 3
    procd_set_param stdout 0
    procd_set_param stderr 1
    procd_close_instance
}
stop_service() {
    rm -f /tmp/kk-car-auto-check.json
}
