#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=20

start_service() {
    test -x /usr/bin/kk-car-voice-gateway || return 1
    test -r /etc/kk-car/private/voice.crt || return 1
    test -r /etc/kk-car/private/voice.key || return 1
    procd_open_instance
    procd_set_param command /usr/bin/kk-car-voice-gateway
    procd_set_param respawn 3600 5 3
    procd_set_param limits nofile="128 128"
    procd_close_instance
}
