#!/bin/sh /etc/rc.common
START=96
STOP=12
USE_PROCD=1
start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/python3 /etc/kk-car/network_health.py run
    procd_set_param nice 10
    procd_set_param respawn 3600 5 5
    procd_set_param stderr 1
    procd_close_instance
}
