#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1
start_service() {
    rm -rf /tmp/kk-car-notify-lock
    procd_open_instance
    procd_set_param command /etc/kk-car/notify-watch.sh
    procd_set_param respawn 3600 5 5
    procd_set_param term_timeout 30
    procd_close_instance
}
shutdown() {
    stop
    rm -rf /tmp/kk-car-notify-lock
    ucode /etc/kk-car/notify-worker.uc shutdown
}
