#!/bin/sh /etc/rc.common
USE_PROCD=1
START=98
STOP=10

start_service() {
    [ -c /dev/spidev0.0 ] || return 1
    [ -x /usr/bin/python3 ] || return 1
    procd_open_instance
    procd_set_param command /usr/bin/python3 /etc/kk-car/epaper.py
    procd_set_param nice 10
    procd_set_param respawn 3600 30 3
    procd_set_param stdout 0
    procd_set_param stderr 1
    procd_close_instance
}
