charon {
    install_routes = no
    install_virtual_ip = yes
    install_virtual_ip_on = ikecar
    keep_alive = 20s
    retransmit_timeout = 2.5
    retransmit_base = 1.6
    retransmit_tries = 5
    plugins {
        socket-default {
            fwmark = 0x10000
        }
        kernel-netlink {
            install_routes_xfrmi = no
        }
    }
}
swanctl {
    load = openssl random
}
